-- Kør denne fil i Supabase SQL Editor

create table if not exists tuner_orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  mechanic text,
  plate text,
  car_class text not null,
  invoice_text text not null,
  total_price integer not null
);

create table if not exists tuner_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references tuner_orders(id) on delete cascade,
  part_key text not null,
  part_name text not null,
  car_class text not null,
  amount integer not null,
  unit_price integer not null,
  total_price integer not null,
  created_at timestamp with time zone default now()
);

-- Simpelt view til statistik over brugte dele
create or replace view tuner_part_usage as
select
  part_key,
  part_name,
  car_class,
  sum(amount) as total_used,
  sum(total_price) as total_value
from tuner_order_items
group by part_key, part_name, car_class
order by total_used desc;

-- Bemærk:
-- Hvis du bruger public anon key direkte fra Netlify, skal du slå RLS fra
-- eller oprette policies. Til intern FiveM-side er det nemmeste:
alter table tuner_orders disable row level security;
alter table tuner_order_items disable row level security;
